name: Build Android app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run Yarn Install
        run: |
          yarn install

      - name: Build application
        run: |
          cd ./android &&
          ./gradlew assembleRelease

      - name: Save APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: APK Release
          path: android/app/build/outputs/apk/release/app-release.apk

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download APK artifact
        uses: actions/download-artifact@v2
        with:
          name: APK Release
          path: app/build/outputs/apk/release/

      - name: Configure Git
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Add APK to Git tag
        run: |
          git tag -a v1.0.0 -m "Release 1.0.0"
          git push origin v1.0.0

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_HUB_RELEASE }}
        with:
          tag_name: v1.0.0
          release_name: Release 1.0.0
          draft: false
          prerelease: false
          body: |
            Add release notes or descriptions here.
